/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto1_tbd2g3;

import java.awt.Color;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;
import java.util.UUID;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author Junior
 */
public class LOG_IN extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    ArrayList<Producto> productos = new ArrayList();
    ArrayList<Laboratorio> laboratorios = new ArrayList();
    ArrayList<Farmacia> farmacias = new ArrayList();
    ArrayList<Cliente> clientes = new ArrayList();
    Cliente admin = new Cliente(0, "admin");
    boolean adminFlag = false;
    boolean userFlag = false;
    ConexionDB con = new ConexionDB();

    public LOG_IN() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        con.Conectar();
        //bt_crearFarmacia.setEnabled(false);
        //bt_crearCliente.setEnabled(false);
        //bt_crearLab.setEnabled(false);
        
    }
    Color fondo;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JD_Lab = new javax.swing.JDialog();
        jPanel16 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        btn_AgregarMedicamento = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        btn_SalirMenuLabs = new javax.swing.JButton();
        JD_AgregarProducto = new javax.swing.JDialog();
        jLabel31 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        tf_namePrd = new javax.swing.JTextField();
        cb_tipo = new javax.swing.JComboBox<>();
        cb_fabricante = new javax.swing.JComboBox<>();
        ftf_pCoste = new javax.swing.JFormattedTextField();
        ftf_pVenta = new javax.swing.JFormattedTextField();
        rb_si = new javax.swing.JRadioButton();
        rb_no = new javax.swing.JRadioButton();
        bt_agregar = new javax.swing.JButton();
        JD_RealizarCompra = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jSeparator5 = new javax.swing.JSeparator();
        JSP_ComprarProducto = new javax.swing.JScrollPane();
        JT_ComprarProducto = new javax.swing.JTable();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        btn_SalirCompra = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        JD_Reabastecimiento = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jSeparator6 = new javax.swing.JSeparator();
        JSP_Reabastecimiento = new javax.swing.JScrollPane();
        JT_Reabastecimiento = new javax.swing.JTable();
        jSpinner2 = new javax.swing.JSpinner();
        jLabel23 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jp_SalirReabastecimiento = new javax.swing.JPanel();
        jl_SalirReabastecimiento = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        JD_InfoFarmacias = new javax.swing.JDialog();
        jPanel24 = new javax.swing.JPanel();
        jSeparator7 = new javax.swing.JSeparator();
        JSP_InfoFarmacias = new javax.swing.JScrollPane();
        JT_InfoFarmacias = new javax.swing.JTable();
        jLabel28 = new javax.swing.JLabel();
        btn_salirInfoFarmacias = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        JD_Inventory = new javax.swing.JDialog();
        jPanel25 = new javax.swing.JPanel();
        jSeparator8 = new javax.swing.JSeparator();
        JSP_Inventario = new javax.swing.JScrollPane();
        JT_Inventario = new javax.swing.JTable();
        jLabel29 = new javax.swing.JLabel();
        jp_SalirInventario = new javax.swing.JPanel();
        jl_SalirInventario = new javax.swing.JLabel();
        JD_CrearFarmacia = new javax.swing.JDialog();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        tf_nameFarmacia = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        tf_direccion = new javax.swing.JTextField();
        bt_crearFarmacia1 = new javax.swing.JButton();
        cb_ownerF = new javax.swing.JComboBox<>();
        jLabel40 = new javax.swing.JLabel();
        JD_CrearLaboratorio = new javax.swing.JDialog();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        tf_nameLab = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        tf_direccionLab = new javax.swing.JTextField();
        bt_crearLab1 = new javax.swing.JButton();
        ftf_infoCntc = new javax.swing.JFormattedTextField();
        jLabel45 = new javax.swing.JLabel();
        JD_CrearCliente = new javax.swing.JDialog();
        jLabel44 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        tf_nameCliente = new javax.swing.JTextField();
        bt_crearCliente1 = new javax.swing.JButton();
        JD_LogIn = new javax.swing.JDialog();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        tf_nameLogIn = new javax.swing.JTextField();
        bt_logIn1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        bt_crearFarmacia = new javax.swing.JButton();
        bt_crearCliente = new javax.swing.JButton();
        bt_crearLab = new javax.swing.JButton();
        bt_logIn = new javax.swing.JButton();
        bt_farmacia = new javax.swing.JButton();
        bt_cliente1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btn_RealizarCompra1 = new javax.swing.JButton();

        jPanel16.setBackground(new java.awt.Color(51, 51, 51));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Menu Principal Laboratorios");

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));

        btn_AgregarMedicamento.setBackground(new java.awt.Color(0, 51, 0));
        btn_AgregarMedicamento.setFont(new java.awt.Font("Georgia", 1, 16)); // NOI18N
        btn_AgregarMedicamento.setForeground(new java.awt.Color(255, 255, 255));
        btn_AgregarMedicamento.setText("Agregar Medicamento");
        btn_AgregarMedicamento.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_AgregarMedicamento.setFocusable(false);
        btn_AgregarMedicamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_AgregarMedicamentoMouseClicked(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(0, 51, 0));
        jButton6.setFont(new java.awt.Font("Georgia", 1, 16)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Medicamentos Almacenados");
        jButton6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton6.setFocusable(false);
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        btn_SalirMenuLabs.setBackground(new java.awt.Color(153, 0, 0));
        btn_SalirMenuLabs.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btn_SalirMenuLabs.setForeground(new java.awt.Color(255, 255, 255));
        btn_SalirMenuLabs.setText("Salir");
        btn_SalirMenuLabs.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_SalirMenuLabs.setFocusable(false);
        btn_SalirMenuLabs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_SalirMenuLabsMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_AgregarMedicamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)))
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_SalirMenuLabs, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4)))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btn_AgregarMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(btn_SalirMenuLabs, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout JD_LabLayout = new javax.swing.GroupLayout(JD_Lab.getContentPane());
        JD_Lab.getContentPane().setLayout(JD_LabLayout);
        JD_LabLayout.setHorizontalGroup(
            JD_LabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JD_LabLayout.setVerticalGroup(
            JD_LabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel31.setBackground(new java.awt.Color(255, 255, 255));
        jLabel31.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Agregar Producto");

        jLabel30.setBackground(new java.awt.Color(255, 255, 255));
        jLabel30.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Nombre");

        jLabel32.setBackground(new java.awt.Color(255, 255, 255));
        jLabel32.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Fabricante");

        jLabel33.setBackground(new java.awt.Color(255, 255, 255));
        jLabel33.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Tipo");

        jLabel34.setBackground(new java.awt.Color(255, 255, 255));
        jLabel34.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Precio Coste");

        jLabel36.setBackground(new java.awt.Color(255, 255, 255));
        jLabel36.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("Protegido por Seguridad Social");

        jLabel35.setBackground(new java.awt.Color(255, 255, 255));
        jLabel35.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Precio Venta");

        cb_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cb_fabricante.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        ftf_pCoste.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        ftf_pVenta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        rb_si.setText("Si");

        rb_no.setText("No");

        bt_agregar.setText("Agregar");
        bt_agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_agregarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout JD_AgregarProductoLayout = new javax.swing.GroupLayout(JD_AgregarProducto.getContentPane());
        JD_AgregarProducto.getContentPane().setLayout(JD_AgregarProductoLayout);
        JD_AgregarProductoLayout.setHorizontalGroup(
            JD_AgregarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_AgregarProductoLayout.createSequentialGroup()
                .addGroup(JD_AgregarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JD_AgregarProductoLayout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jLabel31))
                    .addGroup(JD_AgregarProductoLayout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addGroup(JD_AgregarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_namePrd, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel30)
                            .addComponent(jLabel32)
                            .addComponent(cb_fabricante, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel33)
                            .addComponent(jLabel34)
                            .addComponent(jLabel35)
                            .addGroup(JD_AgregarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(ftf_pVenta, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ftf_pCoste, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cb_tipo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel36)
                            .addGroup(JD_AgregarProductoLayout.createSequentialGroup()
                                .addComponent(rb_si)
                                .addGap(18, 18, 18)
                                .addComponent(rb_no))
                            .addComponent(bt_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(269, Short.MAX_VALUE))
        );
        JD_AgregarProductoLayout.setVerticalGroup(
            JD_AgregarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_AgregarProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_namePrd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb_fabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel34)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ftf_pCoste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel35)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ftf_pVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel36)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JD_AgregarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb_si)
                    .addComponent(rb_no))
                .addGap(18, 18, 18)
                .addComponent(bt_agregar)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        JD_RealizarCompra.setTitle("Comprar Producto - Farmacias DJHR");

        jPanel2.setBackground(new java.awt.Color(0, 51, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator5.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 820, 10));

        JT_ComprarProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        JSP_ComprarProducto.setViewportView(JT_ComprarProducto);

        jPanel2.add(JSP_ComprarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 800, 350));

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jPanel2.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 510, 110, 40));

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Comprar Producto - Farmacias DJHR");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 40));

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Cantidad:");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, 80, 20));

        btn_SalirCompra.setBackground(new java.awt.Color(153, 0, 0));
        btn_SalirCompra.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btn_SalirCompra.setForeground(new java.awt.Color(255, 255, 255));
        btn_SalirCompra.setText("Salir");
        btn_SalirCompra.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_SalirCompra.setFocusable(false);
        btn_SalirCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_SalirCompraMouseClicked(evt);
            }
        });
        jPanel2.add(btn_SalirCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 510, 140, 40));

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Finalizar Pedido");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.setFocusable(false);
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 510, 170, 40));

        jButton2.setBackground(new java.awt.Color(51, 51, 51));
        jButton2.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Agregar Producto");
        jButton2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton2.setFocusable(false);
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 510, 170, 40));

        jLabel5.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Al finalizar, de clic en finalizar pedido.");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel7.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("De la tabla, seleccione algun producto que desee comprar. Posteriormente, especifique la cantidad y de clic en \"Agregar Producto\"");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        javax.swing.GroupLayout JD_RealizarCompraLayout = new javax.swing.GroupLayout(JD_RealizarCompra.getContentPane());
        JD_RealizarCompra.getContentPane().setLayout(JD_RealizarCompraLayout);
        JD_RealizarCompraLayout.setHorizontalGroup(
            JD_RealizarCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 882, Short.MAX_VALUE)
        );
        JD_RealizarCompraLayout.setVerticalGroup(
            JD_RealizarCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(0, 51, 0));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator6.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 240, 20));

        JT_Reabastecimiento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        JSP_Reabastecimiento.setViewportView(JT_Reabastecimiento);

        jPanel5.add(JSP_Reabastecimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 900, -1));

        jSpinner2.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jPanel5.add(jSpinner2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, 110, 40));

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Reabastecimiento ");
        jPanel5.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 40));

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));

        jLabel24.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Realizar Pedido");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 20, 130, 40));

        jLabel25.setBackground(new java.awt.Color(255, 255, 255));
        jLabel25.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Cantidad:");
        jPanel5.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 80, 30));

        jp_SalirReabastecimiento.setBackground(new java.awt.Color(204, 0, 0));

        jl_SalirReabastecimiento.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jl_SalirReabastecimiento.setForeground(new java.awt.Color(255, 255, 255));
        jl_SalirReabastecimiento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_SalirReabastecimiento.setText("Salir");
        jl_SalirReabastecimiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_SalirReabastecimientoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jl_SalirReabastecimientoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jl_SalirReabastecimientoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jp_SalirReabastecimientoLayout = new javax.swing.GroupLayout(jp_SalirReabastecimiento);
        jp_SalirReabastecimiento.setLayout(jp_SalirReabastecimientoLayout);
        jp_SalirReabastecimientoLayout.setHorizontalGroup(
            jp_SalirReabastecimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jl_SalirReabastecimiento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
        );
        jp_SalirReabastecimientoLayout.setVerticalGroup(
            jp_SalirReabastecimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_SalirReabastecimientoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jl_SalirReabastecimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel5.add(jp_SalirReabastecimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 510, -1, -1));

        jPanel7.setBackground(new java.awt.Color(51, 51, 51));

        jLabel26.setBackground(new java.awt.Color(255, 255, 255));
        jLabel26.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Agregar Producto");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel5.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, -1, -1));

        javax.swing.GroupLayout JD_ReabastecimientoLayout = new javax.swing.GroupLayout(JD_Reabastecimiento.getContentPane());
        JD_Reabastecimiento.getContentPane().setLayout(JD_ReabastecimientoLayout);
        JD_ReabastecimientoLayout.setHorizontalGroup(
            JD_ReabastecimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 923, Short.MAX_VALUE)
        );
        JD_ReabastecimientoLayout.setVerticalGroup(
            JD_ReabastecimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)
        );

        jPanel24.setBackground(new java.awt.Color(0, 51, 0));
        jPanel24.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator7.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator7.setForeground(new java.awt.Color(255, 255, 255));
        jPanel24.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 900, 10));

        JT_InfoFarmacias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        JSP_InfoFarmacias.setViewportView(JT_InfoFarmacias);

        jPanel24.add(JSP_InfoFarmacias, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 880, 330));

        jLabel28.setBackground(new java.awt.Color(255, 255, 255));
        jLabel28.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Informacion de Farmacias Administradas");
        jPanel24.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 40));

        btn_salirInfoFarmacias.setBackground(new java.awt.Color(153, 0, 0));
        btn_salirInfoFarmacias.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btn_salirInfoFarmacias.setForeground(new java.awt.Color(255, 255, 255));
        btn_salirInfoFarmacias.setText("Salir");
        btn_salirInfoFarmacias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_salirInfoFarmaciasMouseClicked(evt);
            }
        });
        jPanel24.add(btn_salirInfoFarmacias, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 490, 110, 40));

        jButton3.setBackground(new java.awt.Color(51, 51, 51));
        jButton3.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Ver Inventario");
        jPanel24.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 180, 40));

        jButton4.setBackground(new java.awt.Color(51, 51, 51));
        jButton4.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Reabastecer Farmacia");
        jPanel24.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 490, 210, 40));

        jLabel8.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Para ver el inventario de alguna de ellas, seleccione la farmacia y de clic en \"Ver Inventario\"");
        jPanel24.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel9.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("En esta pagina puede ver todas las farmacias que usted administra.");
        jPanel24.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        javax.swing.GroupLayout JD_InfoFarmaciasLayout = new javax.swing.GroupLayout(JD_InfoFarmacias.getContentPane());
        JD_InfoFarmacias.getContentPane().setLayout(JD_InfoFarmaciasLayout);
        JD_InfoFarmaciasLayout.setHorizontalGroup(
            JD_InfoFarmaciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel24, javax.swing.GroupLayout.DEFAULT_SIZE, 969, Short.MAX_VALUE)
        );
        JD_InfoFarmaciasLayout.setVerticalGroup(
            JD_InfoFarmaciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel24, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
        );

        jPanel25.setBackground(new java.awt.Color(0, 51, 0));
        jPanel25.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator8.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator8.setForeground(new java.awt.Color(255, 255, 255));
        jPanel25.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 900, 10));

        JT_Inventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        JSP_Inventario.setViewportView(JT_Inventario);

        jPanel25.add(JSP_Inventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 850, 360));

        jLabel29.setBackground(new java.awt.Color(255, 255, 255));
        jLabel29.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Inventario de la Farmacia");
        jPanel25.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 40));

        jp_SalirInventario.setBackground(new java.awt.Color(204, 0, 0));

        jl_SalirInventario.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jl_SalirInventario.setForeground(new java.awt.Color(255, 255, 255));
        jl_SalirInventario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_SalirInventario.setText("Salir");
        jl_SalirInventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_SalirInventarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jl_SalirInventarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jl_SalirInventarioMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jp_SalirInventarioLayout = new javax.swing.GroupLayout(jp_SalirInventario);
        jp_SalirInventario.setLayout(jp_SalirInventarioLayout);
        jp_SalirInventarioLayout.setHorizontalGroup(
            jp_SalirInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_SalirInventarioLayout.createSequentialGroup()
                .addComponent(jl_SalirInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        jp_SalirInventarioLayout.setVerticalGroup(
            jp_SalirInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_SalirInventarioLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jl_SalirInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel25.add(jp_SalirInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 490, -1, -1));

        javax.swing.GroupLayout JD_InventoryLayout = new javax.swing.GroupLayout(JD_Inventory.getContentPane());
        JD_Inventory.getContentPane().setLayout(JD_InventoryLayout);
        JD_InventoryLayout.setHorizontalGroup(
            JD_InventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel25, javax.swing.GroupLayout.DEFAULT_SIZE, 956, Short.MAX_VALUE)
        );
        JD_InventoryLayout.setVerticalGroup(
            JD_InventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel25, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );

        jLabel37.setBackground(new java.awt.Color(255, 255, 255));
        jLabel37.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("Crear Farmacia");

        jLabel38.setBackground(new java.awt.Color(255, 255, 255));
        jLabel38.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("Nombre");

        jLabel39.setBackground(new java.awt.Color(255, 255, 255));
        jLabel39.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("Direccion");

        bt_crearFarmacia1.setText("Crear Farmacia");
        bt_crearFarmacia1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_crearFarmacia1MouseClicked(evt);
            }
        });

        cb_ownerF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel40.setBackground(new java.awt.Color(255, 255, 255));
        jLabel40.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("Dueño");

        javax.swing.GroupLayout JD_CrearFarmaciaLayout = new javax.swing.GroupLayout(JD_CrearFarmacia.getContentPane());
        JD_CrearFarmacia.getContentPane().setLayout(JD_CrearFarmaciaLayout);
        JD_CrearFarmaciaLayout.setHorizontalGroup(
            JD_CrearFarmaciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_CrearFarmaciaLayout.createSequentialGroup()
                .addGroup(JD_CrearFarmaciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JD_CrearFarmaciaLayout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addGroup(JD_CrearFarmaciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel37)
                            .addGroup(JD_CrearFarmaciaLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(JD_CrearFarmaciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_nameFarmacia, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                    .addComponent(jLabel38)
                                    .addComponent(tf_direccion, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                    .addComponent(jLabel39)
                                    .addComponent(jLabel40)
                                    .addComponent(cb_ownerF, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(JD_CrearFarmaciaLayout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(bt_crearFarmacia1)))
                .addContainerGap(179, Short.MAX_VALUE))
        );
        JD_CrearFarmaciaLayout.setVerticalGroup(
            JD_CrearFarmaciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_CrearFarmaciaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel38)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_nameFarmacia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel39)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel40)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb_ownerF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bt_crearFarmacia1)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jLabel41.setBackground(new java.awt.Color(255, 255, 255));
        jLabel41.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("Crear Laboratorio");

        jLabel42.setBackground(new java.awt.Color(255, 255, 255));
        jLabel42.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("Nombre");

        jLabel43.setBackground(new java.awt.Color(255, 255, 255));
        jLabel43.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText("Direccion");

        bt_crearLab1.setText("Crear Laboratorio");
        bt_crearLab1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_crearLab1MouseClicked(evt);
            }
        });

        try {
            ftf_infoCntc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel45.setBackground(new java.awt.Color(255, 255, 255));
        jLabel45.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setText("Informacion de Contacto");

        javax.swing.GroupLayout JD_CrearLaboratorioLayout = new javax.swing.GroupLayout(JD_CrearLaboratorio.getContentPane());
        JD_CrearLaboratorio.getContentPane().setLayout(JD_CrearLaboratorioLayout);
        JD_CrearLaboratorioLayout.setHorizontalGroup(
            JD_CrearLaboratorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_CrearLaboratorioLayout.createSequentialGroup()
                .addGroup(JD_CrearLaboratorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JD_CrearLaboratorioLayout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jLabel41))
                    .addGroup(JD_CrearLaboratorioLayout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addGroup(JD_CrearLaboratorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bt_crearLab1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel45)
                            .addComponent(tf_nameLab, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(jLabel42)
                            .addComponent(tf_direccionLab)
                            .addComponent(jLabel43)
                            .addComponent(ftf_infoCntc))))
                .addContainerGap(170, Short.MAX_VALUE))
        );
        JD_CrearLaboratorioLayout.setVerticalGroup(
            JD_CrearLaboratorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_CrearLaboratorioLayout.createSequentialGroup()
                .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel42)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_nameLab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel43)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_direccionLab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel45)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ftf_infoCntc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bt_crearLab1)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jLabel44.setBackground(new java.awt.Color(255, 255, 255));
        jLabel44.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText("Crear Cliente");

        jLabel46.setBackground(new java.awt.Color(255, 255, 255));
        jLabel46.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setText("Nombre");

        bt_crearCliente1.setText("Crear Cliente");
        bt_crearCliente1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_crearCliente1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout JD_CrearClienteLayout = new javax.swing.GroupLayout(JD_CrearCliente.getContentPane());
        JD_CrearCliente.getContentPane().setLayout(JD_CrearClienteLayout);
        JD_CrearClienteLayout.setHorizontalGroup(
            JD_CrearClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_CrearClienteLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(JD_CrearClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel44)
                    .addGroup(JD_CrearClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(bt_crearCliente1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tf_nameCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel46)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        JD_CrearClienteLayout.setVerticalGroup(
            JD_CrearClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_CrearClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel46)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_nameCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(bt_crearCliente1)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jLabel47.setBackground(new java.awt.Color(255, 255, 255));
        jLabel47.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setText("Log In");

        jLabel48.setBackground(new java.awt.Color(255, 255, 255));
        jLabel48.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(255, 255, 255));
        jLabel48.setText("Nombre");

        bt_logIn1.setText("Log In");
        bt_logIn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_logIn1MouseClicked(evt);
            }
        });
        bt_logIn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_logIn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JD_LogInLayout = new javax.swing.GroupLayout(JD_LogIn.getContentPane());
        JD_LogIn.getContentPane().setLayout(JD_LogInLayout);
        JD_LogInLayout.setHorizontalGroup(
            JD_LogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_LogInLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(JD_LogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bt_logIn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tf_nameLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel48)
                    .addGroup(JD_LogInLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel47)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        JD_LogInLayout.setVerticalGroup(
            JD_LogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_LogInLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel48)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_nameLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(bt_logIn1)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Inicial - Farmacias DJHR");

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bt_crearFarmacia.setBackground(new java.awt.Color(0, 51, 0));
        bt_crearFarmacia.setFont(new java.awt.Font("Georgia", 1, 16)); // NOI18N
        bt_crearFarmacia.setForeground(new java.awt.Color(255, 255, 255));
        bt_crearFarmacia.setText("Crear Farmacia");
        bt_crearFarmacia.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bt_crearFarmacia.setFocusable(false);
        bt_crearFarmacia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_crearFarmaciaMouseClicked(evt);
            }
        });
        jPanel1.add(bt_crearFarmacia, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 220, 50));

        bt_crearCliente.setBackground(new java.awt.Color(0, 51, 0));
        bt_crearCliente.setFont(new java.awt.Font("Georgia", 1, 16)); // NOI18N
        bt_crearCliente.setForeground(new java.awt.Color(255, 255, 255));
        bt_crearCliente.setText("Registrar Cliente");
        bt_crearCliente.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bt_crearCliente.setFocusable(false);
        bt_crearCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_crearClienteMouseClicked(evt);
            }
        });
        jPanel1.add(bt_crearCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, 220, 50));

        bt_crearLab.setBackground(new java.awt.Color(0, 51, 0));
        bt_crearLab.setFont(new java.awt.Font("Georgia", 1, 16)); // NOI18N
        bt_crearLab.setForeground(new java.awt.Color(255, 255, 255));
        bt_crearLab.setText("Crear Laboratorio");
        bt_crearLab.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bt_crearLab.setFocusable(false);
        bt_crearLab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_crearLabMouseClicked(evt);
            }
        });
        jPanel1.add(bt_crearLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, 220, 50));

        bt_logIn.setBackground(new java.awt.Color(0, 51, 51));
        bt_logIn.setFont(new java.awt.Font("Georgia", 1, 16)); // NOI18N
        bt_logIn.setForeground(new java.awt.Color(255, 255, 255));
        bt_logIn.setText("Log In");
        bt_logIn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bt_logIn.setFocusable(false);
        bt_logIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_logInMouseClicked(evt);
            }
        });
        jPanel1.add(bt_logIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 440, 120, 40));

        bt_farmacia.setBackground(new java.awt.Color(0, 51, 0));
        bt_farmacia.setFont(new java.awt.Font("Georgia", 1, 16)); // NOI18N
        bt_farmacia.setForeground(new java.awt.Color(255, 255, 255));
        bt_farmacia.setText("Farmacias");
        bt_farmacia.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bt_farmacia.setFocusable(false);
        bt_farmacia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_farmaciaMouseClicked(evt);
            }
        });
        jPanel1.add(bt_farmacia, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 220, 50));

        bt_cliente1.setBackground(new java.awt.Color(0, 51, 0));
        bt_cliente1.setFont(new java.awt.Font("Georgia", 1, 16)); // NOI18N
        bt_cliente1.setForeground(new java.awt.Color(255, 255, 255));
        bt_cliente1.setText("Laboratorios");
        bt_cliente1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bt_cliente1.setFocusable(false);
        bt_cliente1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_cliente1MouseClicked(evt);
            }
        });
        jPanel1.add(bt_cliente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 220, 50));

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Farmacias DJHR");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 220, 40));

        jSeparator9.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator9.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator9.setPreferredSize(new java.awt.Dimension(50, 20));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 600, 10));

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Si usted es un administrador, utilice el boton de \"Log In\" para acceder a demas opciones.");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 580, -1));

        jLabel6.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Bienvenido a Farmacas DJHR.");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 580, -1));

        btn_RealizarCompra1.setBackground(new java.awt.Color(0, 51, 0));
        btn_RealizarCompra1.setFont(new java.awt.Font("Georgia", 1, 16)); // NOI18N
        btn_RealizarCompra1.setForeground(new java.awt.Color(255, 255, 255));
        btn_RealizarCompra1.setText("Realizar Compra ");
        btn_RealizarCompra1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_RealizarCompra1.setFocusable(false);
        btn_RealizarCompra1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_RealizarCompra1MouseClicked(evt);
            }
        });
        jPanel1.add(btn_RealizarCompra1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 220, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 653, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jl_SalirReabastecimientoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_SalirReabastecimientoMouseClicked
        JD_Reabastecimiento.dispose();
        AbrirVentana(JD_InfoFarmacias);
    }//GEN-LAST:event_jl_SalirReabastecimientoMouseClicked

    private void jl_SalirReabastecimientoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_SalirReabastecimientoMouseEntered
        fondo = jp_SalirReabastecimiento.getBackground();
        jp_SalirReabastecimiento.setBackground(Color.red);
    }//GEN-LAST:event_jl_SalirReabastecimientoMouseEntered

    private void jl_SalirReabastecimientoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_SalirReabastecimientoMouseExited
        jp_SalirReabastecimiento.setBackground(fondo);
    }//GEN-LAST:event_jl_SalirReabastecimientoMouseExited

    private void jl_SalirInventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_SalirInventarioMouseClicked
        JD_Inventory.dispose();
        AbrirVentana(JD_InfoFarmacias);
    }//GEN-LAST:event_jl_SalirInventarioMouseClicked

    private void jl_SalirInventarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_SalirInventarioMouseEntered
        fondo = jp_SalirInventario.getBackground();
        jp_SalirInventario.setBackground(Color.red);
    }//GEN-LAST:event_jl_SalirInventarioMouseEntered

    private void jl_SalirInventarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_SalirInventarioMouseExited
        jp_SalirInventario.setBackground(fondo);
    }//GEN-LAST:event_jl_SalirInventarioMouseExited

    private void bt_agregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_agregarMouseClicked
        Producto p = new Producto();
        p.setName(tf_namePrd.getText());
        p.setFabricante((String) cb_fabricante.getSelectedItem());
        p.setTipo((String) cb_tipo.getSelectedItem());
        p.setP_coste(Double.parseDouble(ftf_pCoste.getText()));
        p.setP_venta(Double.parseDouble(ftf_pVenta.getText()));
        p.setId("P" + UUID.randomUUID().toString());
        if (rb_si.isSelected()) {
            p.setS_s(true);
            productos.add(p);
            JD_AgregarProducto.dispose();
            this.setVisible(true);
        } else if (rb_no.isSelected()) {
            p.setS_s(false);
            productos.add(p);
            JD_AgregarProducto.dispose();
            this.setVisible(true);
            
            
            
            
        } else {
            JOptionPane.showMessageDialog(JD_AgregarProducto, "Tiene que seleccionar si esta protegido o no", "Seleccion Invalida", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bt_agregarMouseClicked

    private void bt_crearFarmacia1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_crearFarmacia1MouseClicked
        Farmacia f = new Farmacia();
        f.setId("F" + UUID.randomUUID().toString());
        f.setName(tf_nameFarmacia.getText());
        f.setAddress(tf_direccion.getText());
        f.setOwner((Farmaceutico) cb_ownerF.getSelectedItem());
        tf_nameFarmacia.setText("");
        tf_direccion.setText("");
        farmacias.add(f);
        JD_CrearFarmacia.dispose();
        this.setVisible(true);
    }//GEN-LAST:event_bt_crearFarmacia1MouseClicked

    private void bt_crearFarmaciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_crearFarmaciaMouseClicked
        AbrirVentana(JD_CrearFarmacia);
        this.setVisible(false);
    }//GEN-LAST:event_bt_crearFarmaciaMouseClicked

    private void bt_crearLab1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_crearLab1MouseClicked
        Laboratorio l = new Laboratorio();
        l.setId("L" + UUID.randomUUID().toString());
        l.setAddress(tf_direccionLab.getText());
        l.setInfo_cntc(ftf_infoCntc.getText());
        l.setName(tf_nameLab.getText());
        tf_direccionLab.setText("");
        ftf_infoCntc.setText("");
        tf_nameLab.setText("");
        laboratorios.add(l);
        JD_CrearLaboratorio.dispose();
        this.setVisible(false);
    }//GEN-LAST:event_bt_crearLab1MouseClicked

    private void bt_crearCliente1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_crearCliente1MouseClicked
        Cliente c = new Cliente();
        c.setId(Integer.parseInt(UUID.randomUUID().toString()));
        c.setUser(tf_nameCliente.getText());
        tf_nameCliente.setText("");
        tf_direccionLab.setText("");
        ftf_infoCntc.setText("");
        clientes.add(c);
        JD_CrearCliente.dispose();
        this.setVisible(true);
    }//GEN-LAST:event_bt_crearCliente1MouseClicked

    private void bt_crearClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_crearClienteMouseClicked
        AbrirVentana(JD_CrearCliente);
        this.setVisible(false);
    }//GEN-LAST:event_bt_crearClienteMouseClicked

    private void bt_crearLabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_crearLabMouseClicked
        AbrirVentana(JD_CrearLaboratorio);
        this.setVisible(false);
    }//GEN-LAST:event_bt_crearLabMouseClicked

    private void bt_logIn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_logIn1MouseClicked
        if (!tf_nameLogIn.getText().isBlank()) {
            for (Cliente cliente : clientes) {
                if (tf_nameLogIn.getText().equals(cliente.getUser())) {
                    userFlag = true;
                    if (tf_nameLogIn.getText().equals("admin")) {
                        adminFlag = true;
                        bt_crearFarmacia.setEnabled(true);
                        bt_crearCliente.setEnabled(true);
                        bt_crearLab.setEnabled(true);
                    }
                }
            }
            tf_nameLogIn.setText("");
            JD_LogIn.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Ingrese nombre de Usuario", "WRONG_USER", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bt_logIn1MouseClicked

    private void bt_farmaciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_farmaciaMouseClicked
        this.setVisible(false);
        AbrirVentana(JD_InfoFarmacias);
    }//GEN-LAST:event_bt_farmaciaMouseClicked

    private void bt_cliente1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_cliente1MouseClicked
        this.setVisible(false);
        AbrirVentana(JD_Lab);
    }//GEN-LAST:event_bt_cliente1MouseClicked

    private void bt_logInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_logInMouseClicked
        AbrirVentana(JD_LogIn);
    }//GEN-LAST:event_bt_logInMouseClicked

    private void btn_RealizarCompra1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_RealizarCompra1MouseClicked
        this.setVisible(false);
        AbrirVentana(JD_RealizarCompra);
    }//GEN-LAST:event_btn_RealizarCompra1MouseClicked

    private void bt_logIn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_logIn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_logIn1ActionPerformed

    private void btn_salirInfoFarmaciasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_salirInfoFarmaciasMouseClicked
        JD_InfoFarmacias.dispose();
        this.setVisible(true);
    }//GEN-LAST:event_btn_salirInfoFarmaciasMouseClicked

    private void btn_SalirCompraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SalirCompraMouseClicked
        JD_RealizarCompra.dispose();
        this.setVisible(true);
    }//GEN-LAST:event_btn_SalirCompraMouseClicked

    private void btn_AgregarMedicamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_AgregarMedicamentoMouseClicked
        // Codigo Prueba para la base de datos
        con.insertPerson("250", "Rodrigo", "Vasquez", 19);
    }//GEN-LAST:event_btn_AgregarMedicamentoMouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6MouseClicked

    private void btn_SalirMenuLabsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SalirMenuLabsMouseClicked
        JD_Lab.dispose();
        this.setVisible(true);
    }//GEN-LAST:event_btn_SalirMenuLabsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LOG_IN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LOG_IN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LOG_IN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LOG_IN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LOG_IN().setVisible(true);
            }
        });
    }

    public void AbrirVentana(JDialog ventana) {
        ventana.pack();
        ventana.setModal(false);
        ventana.setLocationRelativeTo(this);
        ventana.setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog JD_AgregarProducto;
    private javax.swing.JDialog JD_CrearCliente;
    private javax.swing.JDialog JD_CrearFarmacia;
    private javax.swing.JDialog JD_CrearLaboratorio;
    private javax.swing.JDialog JD_InfoFarmacias;
    private javax.swing.JDialog JD_Inventory;
    private javax.swing.JDialog JD_Lab;
    private javax.swing.JDialog JD_LogIn;
    private javax.swing.JDialog JD_Reabastecimiento;
    private javax.swing.JDialog JD_RealizarCompra;
    private javax.swing.JScrollPane JSP_ComprarProducto;
    private javax.swing.JScrollPane JSP_InfoFarmacias;
    private javax.swing.JScrollPane JSP_Inventario;
    private javax.swing.JScrollPane JSP_Reabastecimiento;
    private javax.swing.JTable JT_ComprarProducto;
    private javax.swing.JTable JT_InfoFarmacias;
    private javax.swing.JTable JT_Inventario;
    private javax.swing.JTable JT_Reabastecimiento;
    private javax.swing.JButton bt_agregar;
    private javax.swing.JButton bt_cliente1;
    private javax.swing.JButton bt_crearCliente;
    private javax.swing.JButton bt_crearCliente1;
    private javax.swing.JButton bt_crearFarmacia;
    private javax.swing.JButton bt_crearFarmacia1;
    private javax.swing.JButton bt_crearLab;
    private javax.swing.JButton bt_crearLab1;
    private javax.swing.JButton bt_farmacia;
    private javax.swing.JButton bt_logIn;
    private javax.swing.JButton bt_logIn1;
    private javax.swing.JButton btn_AgregarMedicamento;
    private javax.swing.JButton btn_RealizarCompra1;
    private javax.swing.JButton btn_SalirCompra;
    private javax.swing.JButton btn_SalirMenuLabs;
    private javax.swing.JButton btn_salirInfoFarmacias;
    private javax.swing.JComboBox<String> cb_fabricante;
    private javax.swing.JComboBox<String> cb_ownerF;
    private javax.swing.JComboBox<String> cb_tipo;
    private javax.swing.JFormattedTextField ftf_infoCntc;
    private javax.swing.JFormattedTextField ftf_pCoste;
    private javax.swing.JFormattedTextField ftf_pVenta;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JLabel jl_SalirInventario;
    private javax.swing.JLabel jl_SalirReabastecimiento;
    private javax.swing.JPanel jp_SalirInventario;
    private javax.swing.JPanel jp_SalirReabastecimiento;
    private javax.swing.JRadioButton rb_no;
    private javax.swing.JRadioButton rb_si;
    private javax.swing.JTextField tf_direccion;
    private javax.swing.JTextField tf_direccionLab;
    private javax.swing.JTextField tf_nameCliente;
    private javax.swing.JTextField tf_nameFarmacia;
    private javax.swing.JTextField tf_nameLab;
    private javax.swing.JTextField tf_nameLogIn;
    private javax.swing.JTextField tf_namePrd;
    // End of variables declaration//GEN-END:variables
}
